modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Teenkung/PackForge/issues"

[[mods]]
modId="packforge"
version="${version}"
displayName="PackForge"
displayURL="https://github.com/Teenkung/PackForge"
logoFile="assets/packforge/icon.png"
authors="Teenkung123"
description="Faster pack reloads and atlas overflow recovery for large resource packs."

[[mixins]]
config="packforge.fabric.mixins.json"

[[mixins]]
config="packforge.fabric.client.mixins.json"

[[dependencies.packforge]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.packforge]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
