pluginManagement {
	def rootProperties = new Properties()
	file("../../gradle.properties").withInputStream { rootProperties.load(it) }
	def rootProperty = { String name ->
		gradle.startParameter.projectProperties.get(name) ?: rootProperties.getProperty(name)
	}

	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}

	plugins {
		id 'net.fabricmc.fabric-loom' version rootProperty("loom_version")
	}
}

rootProject.name = 'packforge-fabric'
