package com.teenkung.packforge.config;

/** Exact identifiers consumed from generated packforge-capabilities.properties. */
public enum PackForgeCapability {
	RESOURCE_PACK_INDEX,
	ZIP_READ_POOL,
	LOADER_TIMINGS,
	RELOAD_LISTENER_TIMINGS,
	SHADER_STALL_DIAGNOSTICS,
	IMMEDIATELY_FAST_FONT_ATLAS_COMPAT,
	LOADING_STATUS_OVERLAY,
	LOADING_FADE_CONTROL,
	RELOAD_SUMMARY_TOAST,
	MODEL_UV_TRANSPARENCY_CLAMP,
	FONT_RELOAD_DIAGNOSTICS,
	FONT_PROVIDER_PRESELECTION,
	FONT_BITMAP_CACHE,
	ATLAS_PHASE_TIMINGS,
	ATLAS_MIP_PARALLEL,
	ATLAS_DECODE_BATCHING,
	MODEL_PARSE_BATCHING,
	MODEL_PARSE_TIMINGS,
	MODEL_ADAPTIVE_BATCHING,
	MODEL_DUPLICATE_CACHE,
	ATLAS_CAP,
	ATLAS_RETRY,
	STARTUP_OPTIMIZER,
	STARTUP_TIMINGS,
	STARTUP_STATUS_OVERLAY,
	STARTUP_EXECUTOR_TUNING,
	STARTUP_ASYNC_DATA,
	STARTUP_ASYNC_CLASS_SCAN,
	STARTUP_ASYNC_FONT_ATLAS
}
